title: Diana Rocío Galindo # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
 Data projects lover
 <br><br>
 <a href="https://www.linkedin.com/in/drgalindog/">LinkedIn</a>
 <br> 
 <br>

  
theme: jekyll-theme-minimal
